# version: '3'
version: '4'
services:
  web:
    build: . # find Dockerfile in current directory
    ports:
      - "8080:8080" # map port 8080 on host to port 8080 in container (port forwarding)
  db:
    image: "mysql" # use mysql image from docker hub
    environment: # set environment variables
      - MYSQL_ROOT_PASSWORD= password
    volumes: # create a volume called db-data 
      - db-data:/foo

# volumes: # create a volume called db-data (can be used by multiple containers) (store databse data across multiple containers)
#   db-data: 