# version: '3'
version: '4'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  # db:
  #   image: "mysql"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD= password
  #   volumes:
  #     - db-data:/foo

# volumes:
#   db-data: